parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: sf2qotd
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 60af06df0d92b47ca2c5d6097f230e7ba245d216
    database_path: null
